get http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
get http://localhost:3000/todos/?status=IN%20PROGRESS
###
get http://localhost:3000/todos/?priority=HIGH
###
get http://localhost:3000/todos/?search_q=Play
###
get http://localhost:3000/todos/14
###
post http://localhost:3000/todos/
Content-Type:application/json 

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###
put http://localhost:3000/todos/10
Content-Type: application/json

 {
      "status": "DONE"
}
###
delete http://localhost:3000/todos/12